# dist: https://docs.travis-ci.com/user/reference/linux#sts=Using%20Ubuntu%20Linux%20distributions%20#
dist: focal
#dist: bionic

env:
  global:
    - XDEBUG_MODE=coverage
    
# php versions and dists: https://docs.travis-ci.com/user/languages/php
language: php

php:
  - '8.0'
  - '8.1'
  - nightly

matrix:
  allow_failures:
    - php: '8.1'
    - php: nightly

addons:
  mariadb: '10.5'

branches:
  only:
    # tests may fail
    - unstable
    # tests should not fail (release candidate for major/minor version)
    - testing
    # tests dont fail (release of versions or hotfixes)
    - stable
    - /[0-9]+\.[0-9]+\.[0-9]+/

cache:
  directories:
    - $HOME/.composer/cache/

before_install:
  - sudo mysql -e 'drop user if exists travis@localhost;'
  - sudo mysql -e 'drop user if exists travis@127.0.0.1;'
  - sudo mysql -e 'create user travis@localhost;'
  - sudo mysql -e 'create user travis@127.0.0.1;'
  - sudo mysql -e 'DROP DATABASE IF EXISTS mumsys_tests;'
  - sudo mysql -e 'CREATE DATABASE IF NOT EXISTS mumsys_tests;'
  - sudo mysql -e 'GRANT ALL ON *.* TO travis@localhost;' || true

install:
    - travis_wait 30
    - travis_retry composer update --no-interaction --prefer-source

before_script: 
# having coverage via travis-ci output
#  - phpenv config-rm xdebug.ini || true
  - sleep 5
  - git submodule update --init --recursive
  - sleep 5
  - ./phing travis
  - cat tests/config/default.php
  - cat tests/config/credentials.php

script: 
#  - ./phing all
   - ./phing check
#  - ./phing test
   - ./tests/runTestsCoverageCreate.sh --coverage-text
   - ./phing api
#  - ./tests/runBenchmarks.sh

#after_success:
#    - travis_retry php vendor/bin/coveralls -v
