language: php
php:
# Off because of phpunnit version and dependency issues
#  - '5.4' 
# Off because of phpunnit version and dependency issues
#  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
# Off because its too upfront
#  - nightly
  
before_script: 
  - cd tests
  - composer require --dev phpunit/phpunit ^5.7
# phpunit --configuration phpunit.xml
script: vendor/bin/phpunit
