env:
  global:
    - XDEBUG_MODE=coverage
    
    
language: php

php:
  - '8.0'
  - nightly

matrix:
  allow_failures:
    - php: nightly

addons:
  mariadb: '10.5'

branches:
  only:
    - unstable
    - stable
    - /[0-9]+\.[0-9]+\.[0-9]+/

cache:
  directories:
    - $HOME/.composer/cache/

install:
#  - travis_retry composer install --no-interaction --prefer-source
    - travis_retry composer update --no-interaction --prefer-source

before_script: 
# having coverage via travis-ci output
#  - phpenv config-rm xdebug.ini || true
  - sleep 5
  - git submodule update --init --recursive
  - sleep 5
  - ./phing travis
  - echo "<?php return array('debug' => true, 'database' => array('type' => 'mysql:mysqli', 'host' => 'localost', 'port' => '3306', 'username' => 'root', 'password' => '', 'db' => 'mumsys', 'charset' => 'utf8', 'compress' => false, 'throwErrors' => true, 'debug' => false, 'socket' => false, 'tables' => array('table_access' => 'mumsys_access', 'table_programs' => 'mumsys_programs', 'table_blocks' => 'mumsys_blocks', 'table_sessions' => 'mumsys_sessions', 'table_sessionsuser' => 'mumsys_sessionsuser', 'table_config' => 'mumsys_config')));" > tests/config/default.php
  - echo "<?php return array('database' => array('type' => 'mysql:mysqli', 'host' => 'localhost', 'port' => '3306', 'username' => 'root', 'password' => '','db' => 'mumsys', 'charset' => 'utf8', 'compress' => false, 'throwErrors' => true, 'debug' => false, 'socket' => false));" > tests/config/credentials.php
  - echo "OK";

script: 
  - ./phing check
  - ./phing test
#  - ./vendor/bin/phpunit --coverage-text

#after_success:
#    - travis_retry php vendor/bin/coveralls -v
