language: php
php:
    # Off because of phpunnit version and dependency issues
    #  - '5.4' 
    # Off because of phpunnit version and dependency issues
    #  - '5.5'
    - '5.6'
    - '7.0'
    - '7.1'
    # bugos phpunit / php possible:  
    # - '7.2'
    # Off, too upfront
    #  - nightly
  
sudo: false

before_script: 
    #  - curl -s http://getcomposer.org/installer | php
    # - php composer.phar install --no-interaction
    - composer install
    - cd tests

script: ../vendor/bin/phpunit --no-coverage

#after_success:
    # <logging>
    #    <log type="coverage-clover" target="clover.xml"/>
    # </logging>
#    - travis_retry php vendor/bin/coveralls -v
